version: '3.8'

services:
  db:
    image: mysql:8.1.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: wallet
      MYSQL_USER: wallet
      MYSQL_PASSWORD: wallet
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql



  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    environment:
     - REDIS_REPLICATION_MODE=master
    volumes:
      - redis:/redis
    command: redis-server


  wallet_app:
    build: .
    command: sh -c "./entry.sh"
    restart: on-failure
    env_file: .env.docker
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
  redis: