# Generated by Django 4.2.5 on 2023-12-17 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallet_app", "0002_alter_wallet_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wallet",
            options={"ordering": ["-id"]},
        ),
    ]
