# Generated by Django 4.2.5 on 2023-12-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deposits", "0002_rename_status_deposit_deposit_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deposit",
            name="deposit_status",
        ),
        migrations.RemoveField(
            model_name="deposit",
            name="transaction_status",
        ),
        migrations.AddField(
            model_name="deposit",
            name="status",
            field=models.IntegerField(choices=[(0, "Pending"), (1, "Done"), (2, "Failed")], default=0),
        ),
    ]
