# Generated by Django 4.2.5 on 2023-12-23 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wallet_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="W2WDelay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("tracker_id", models.CharField(default=None, max_length=255, null=True)),
                ("apply_at", models.DateTimeField()),
                ("status", models.IntegerField(choices=[(0, "Pending"), (5, "Done"), (10, "Failed")], default=0)),
                ("reject_status", models.IntegerField(default=None, null=True)),
                ("reject_description", models.CharField(default=None, max_length=1000, null=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    "destination_wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="w2ws_delay_destinations",
                        to="wallet_app.wallet",
                    ),
                ),
                (
                    "source_wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="w2ws_delay_source", to="wallet_app.wallet"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="W2W",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("tracker_id", models.CharField(default=None, max_length=255, null=True)),
                ("status", models.IntegerField(choices=[(0, "Pending"), (5, "Done"), (10, "Failed")], default=0)),
                ("reject_status", models.IntegerField(default=None, null=True)),
                ("reject_description", models.CharField(default=None, max_length=1000, null=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    "destination_wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="w2ws_destinations", to="wallet_app.wallet"
                    ),
                ),
                (
                    "source_wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="w2ws_source", to="wallet_app.wallet"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="w2wdelay",
            constraint=models.UniqueConstraint(fields=("tracker_id",), name="unique_tracker_id_w2w_delay"),
        ),
        migrations.AddConstraint(
            model_name="w2w",
            constraint=models.UniqueConstraint(fields=("tracker_id",), name="unique_tracker_id_w2w"),
        ),
    ]
