# Generated by Django 4.2.5 on 2023-12-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("w2w", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="w2w",
            name="tracker_id",
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
