# Generated by Django 4.2.5 on 2023-12-24 16:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("wallet_app", "0001_initial"),
        ("w2w", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="w2wdelay",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="w2wdelay",
            name="unique_tracker_id_w2w_delay",
        ),
        migrations.RemoveField(
            model_name="w2wdelay",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="w2wdelay",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="w2wdelay",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="w2wdelay",
            name="destination_wallet",
        ),
        migrations.RemoveField(
            model_name="w2wdelay",
            name="id",
        ),
        migrations.RemoveField(
            model_name="w2wdelay",
            name="reject_description",
        ),
        migrations.RemoveField(
            model_name="w2wdelay",
            name="reject_status",
        ),
        migrations.RemoveField(
            model_name="w2wdelay",
            name="source_wallet",
        ),
        migrations.RemoveField(
            model_name="w2wdelay",
            name="status",
        ),
        migrations.RemoveField(
            model_name="w2wdelay",
            name="tracker_id",
        ),
        migrations.AddField(
            model_name="w2wdelay",
            name="w2w_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="w2w.w2w",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="w2w",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="w2w",
            name="destination_wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_destination_wallet",
                to="wallet_app.wallet",
            ),
        ),
        migrations.AlterField(
            model_name="w2w",
            name="source_wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_source_wallet",
                to="wallet_app.wallet",
            ),
        ),
    ]
