# Generated by Django 4.2.5 on 2023-12-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("w2w", "0006_rename_status_w2wdelay_transaction_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="w2w",
            name="transaction_status",
            field=models.IntegerField(choices=[(0, "Pending"), (1, "Done"), (2, "Failed")], default=0),
        ),
        migrations.AlterField(
            model_name="w2wdelay",
            name="transaction_status",
            field=models.IntegerField(choices=[(0, "Pending"), (1, "Done"), (2, "Failed")], default=0),
        ),
    ]
