# Generated by Django 4.2.5 on 2023-12-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w2w', '0007_alter_w2w_transaction_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='w2w',
            old_name='transaction_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='w2wdelay',
            old_name='transaction_status',
            new_name='status',
        ),
    ]
