# Generated by Django 4.2.5 on 2023-12-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w2w', '0008_rename_transaction_status_w2w_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='w2w',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='w2wdelay',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='w2w',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (5, 'Done'), (10, 'Failed')], default=0),
        ),
        migrations.AlterField(
            model_name='w2wdelay',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (5, 'Done'), (10, 'Failed')], default=0),
        ),
    ]
