# Generated by Django 4.2.5 on 2023-12-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("w2w", "0009_alter_w2w_options_alter_w2wdelay_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="w2w",
            name="tracker_id",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="w2w",
            constraint=models.UniqueConstraint(
                fields=("tracker_id",),
                name="unique_tracker_id_w2w",
                violation_error_message="mf ur tracker id is duplicated idiot mffff!",
            ),
        ),
    ]
