# Generated by Django 4.2.5 on 2023-12-23 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveBigIntegerField(default=None, editable=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.IntegerField()),
                ("type", models.IntegerField(choices=[(0, "Deposit"), (1, "Withdrew")])),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="actions", to="transaction.transaction"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
