# Generated by Django 4.2.5 on 2023-12-23 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wallet_app", "0001_initial"),
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="actions", to="wallet_app.wallet"
            ),
        ),
    ]
