# Generated by Django 4.2.5 on 2023-09-23 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0002_withdrewtowallet_deposittowallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposittowallet",
            name="amount",
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name="withdrewtowallet",
            name="amount",
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
