# Generated by Django 4.2.5 on 2023-12-23 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0003_remove_action_type_action_action_type_action_io"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="action_type",
            field=models.IntegerField(
                choices=[(0, "W2W"), (1, "Deposit"), (2, "Withdrew"), (3, "Wage"), (4, "W2W Delay")], default=None
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="action",
            name="description",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="action",
            name="io",
            field=models.BooleanField(
                default=None,
                help_text="Determine the action is Input to wallet or Output. True means Input and False means Output.",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="actions", to="transaction.transaction"
            ),
        ),
    ]
