# Generated by Django 4.2.5 on 2023-12-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0005_alter_action_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="mirror_code",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
