# Generated by Django 4.2.5 on 2023-12-10 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('transaction', '0005_remove_transaction_tracker_id_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='transaction',
            name='content_type',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
