# Generated by Django 4.2.5 on 2023-12-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0007_alter_transaction_object_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="action",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="transaction",
            name="object_id",
            field=models.PositiveBigIntegerField(default=None, editable=False),
        ),
    ]
