# Generated by Django 4.2.5 on 2023-12-23 18:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wallet_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Withdrew",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("tracker_id", models.CharField(default=None, max_length=255, null=True)),
                ("status", models.IntegerField(choices=[(0, "Pending"), (5, "Done"), (10, "Failed")], default=0)),
                ("reject_status", models.IntegerField(default=None, null=True)),
                ("reject_description", models.CharField(default=None, max_length=1000, null=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="wallet_app.wallet")),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="withdrew",
            constraint=models.UniqueConstraint(fields=("tracker_id",), name="unique_tracker_id_withdraw"),
        ),
    ]
