# Generated by Django 4.2.5 on 2023-12-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrews', '0002_rename_status_withdrew_withdrew_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrew',
            name='transaction_status',
        ),
        migrations.RemoveField(
            model_name='withdrew',
            name='withdrew_status',
        ),
        migrations.AddField(
            model_name='withdrew',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Done'), (2, 'Failed')], default=0),
        ),
    ]
