# Generated by Django 4.2.5 on 2023-12-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scopes", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="scopes",
            field=models.ManyToManyField(to="scopes.scope"),
        ),
    ]
